---
title: "measles_risk_prediction_include_catchment"
output: html_document
date: "2025-07-11"
---

```{r setup, include=FALSE}

library(tidycensus)
library(dplyr)
library(readxl)
library(tidyr)
library(stringr)
library(sf)
library(ggplot2)
library(tibble)
library(tigris)
library(lubridate)
library(purrr)
library(pROC)
library(precrec)
source("/Users/dk29776/Dropbox/UTAustin/measles/code/gravity_model_function.R")

tx_county_area <- get_acs(
  geography = "county",
  variables = "B01003_001",
  state = "TX",
  geometry = TRUE,
  year = 2022
) %>%
  rename(population = estimate) %>%
  dplyr::mutate(area_sqkm = as.numeric(st_area(geometry)) / 10^6,
                area_sqmi = area_sqkm * 0.386102,
                pop_density = population / area_sqmi) %>%
  dplyr::select(NAME, population, area_sqmi, pop_density) %>%
  dplyr::mutate(NAME = str_remove(NAME, " County")) %>%  # " County" remove
  separate(NAME, into = c("county", "state"), sep = ", ", remove = FALSE) %>%
  dplyr::select(-NAME)

df <- read_excel("/Users/dk29776/Dropbox/UTAustin/measles/data/UT_Measles_update_17062025.xlsx")
df_filter <- df %>%
  select(hospitalized = `Hospitalized?`, age = Age, 
         county = `Home County`,
         vaccine_status = `Vaccine Status (The unvaccinated/unknown category includes people with no documented doses of measles vaccine more than 14 days before symptom onset)`,
         date_of_rash_onset = `Date of Rash Onset (If rash onset date not available, the following hierarchy is used for date: symptom onset date, specimen collection date, hospital admission date, or date reported to the region)`) %>%
  dplyr::mutate(date_of_rash_onset = as.Date(date_of_rash_onset),
                end_date = date_of_rash_onset + (6 - lubridate::wday(date_of_rash_onset, week_start = 1)))

df_fitting <- df_filter %>%
  dplyr::group_by(county, end_date) %>%
  dplyr::summarise(inc = n()) %>%# ,
  arrange(end_date)



first_onset_data <- df_fitting %>% dplyr::group_by(county) %>%
  filter(inc > 0) %>%
  dplyr::summarise(first_onset_date = min(end_date)) %>%
  dplyr::mutate(first_onset = 1)

gravity_input <- read.csv("/Users/dk29776/Dropbox/UTAustin/measles/data/gravity_input.csv")
```

```{r measles_map}
first_onset_data %>%
  left_join(tx_county_area, by = "county") %>%
  ggplot() +
  geom_sf(aes(geometry = geometry, fill = first_onset), color = NA) +  # main layer
  geom_sf(data = tx_county_area, fill = NA, color = "black", size = 0.3) +  # outlines
  theme_minimal()

```



### Gradient Boosting

```{r function_GBM}

library(xgboost)
library(caret)
library(Matrix)


lag_sum_cal_G <- function(gravity_input_measles, delta, alpha, alpha_d, alpha_c){
  gravity_input_measles <- gravity_input_measles %>%
    mutate(across(where(is.numeric), ~replace_na(., 0)))
  df <- gravity_input_measles %>%
    dplyr::mutate(
      log_pop_x = log1p(population_x),
      log_visits = log1p(visits + 1e-5),
      log_dist = log1p(dist_km + 1e-5),
      log_catchment_flow = log1p(catchment_flow + 1e-5),
     
      
      G_lag_mob = (inc_lag_sum * log_pop_x^delta) / (log_visits^alpha),
      G_lag_dist = (inc_lag_sum * log_pop_x^delta) / (log_dist^alpha_d),
      G_lag_catchment = (inc_lag_sum * log_pop_x^delta) / (log_catchment_flow^alpha_c)
    ) %>%
    dplyr::group_by(county_x, as_of, first_onset, vaccine,
                    pct_age_0_4, pct_age_5_9, pct_age_10_17,
                    pct_age_18_64, pct_age_65_plus, mennonite) %>%
    dplyr::summarise(
      G_mob = sum(G_lag_mob, na.rm = TRUE),
      G_dist = sum(G_lag_dist, na.rm = TRUE),
      G_catchment = sum(G_lag_catchment, na.rm = TRUE),
      .groups = "drop"
    )
  return(df)
}


gbm_fitting <- function(gravity_input_measles, delta, alpha, alpha_d, alpha_c, gravity_test_measles, data_filter = NULL){
  df_train <- lag_sum_cal_G(gravity_input_measles, delta, alpha, alpha_d, alpha_c) %>%
    drop_na()
  
  if(!is.null(data_filter)){
    df_train <- df_train %>%
      mutate(as_of = as.Date(as_of)) %>%  # 문자열을 날짜로 변환
      group_by(county_x) %>%
      slice_max(as_of, n = 1) %>%
      ungroup()
  }
  
  df_train_scaled <- df_train %>%
    dplyr::mutate(across(
      .cols = -c(county_x, as_of, first_onset),
      .fns = scale
    ))
  
  df_test <- lag_sum_cal_G(gravity_test_measles, delta, alpha, alpha_d, alpha_c) %>%
    drop_na()
  
  if(!is.null(data_filter)){
    df_test <- df_test %>%
      mutate(as_of = as.Date(as_of)) %>%  # 문자열을 날짜로 변환
      group_by(county_x) %>%
      slice_max(as_of, n = 1) %>%
      ungroup()
  }
  
  df_test_scaled <- df_test %>%
    dplyr::mutate(across(
      .cols = -c(county_x, as_of, first_onset),
      .fns = scale
    ))
  
  train_X <- as.matrix(df_train_scaled %>% select(-county_x, -as_of, -first_onset))
  train_y <- df_train$first_onset
  dtrain <- xgb.DMatrix(data = train_X, label = train_y)
  
  test_X <- as.matrix(df_test_scaled %>% select(-county_x, -as_of, -first_onset))
  test_y <- df_test$first_onset
  dtest <- xgb.DMatrix(data = test_X, label = test_y)
  
  scale_pos_weight <- length(which(train_y==0)) / length(which(train_y==1))
  xgb_fit <- xgb.train(
    params = list(
      objective = "binary:logistic",
      eval_metric = "logloss",
      max_depth = 4,
      eta = 0.1,
      scale_pos_weight = scale_pos_weight
    ),
    data = dtrain,
    nrounds = 30,
    verbose = 0
  )
  
  preds <- predict(xgb_fit, dtest)
  return(list(preds = preds, df_test_scaled = df_test_scaled, test_y = test_y, xgb_fit = xgb_fit))
}

loss_fn_gbm <- function(params, gravity_input_measles, gravity_test_measles, data_filter = NULL) {
  delta <- params[1]
  alpha <- params[2]
  alpha_d <- params[3]
  alpha_c <- params[4]
  
  gmb_res <- gbm_fitting(gravity_input_measles, delta, alpha, alpha_d, alpha_c, gravity_test_measles, data_filter = NULL)
  preds = gmb_res$preds
  test_y = gmb_res$test_y
  
  logloss <- -mean(test_y * log(preds + 1e-6) + (1 - test_y) * log(1 - preds + 1e-6))
  
  return(logloss)
}

gbm_fitting_final <- function(train_date, test_date, data_filter = NULL){
  gravity_input_measles <- gravity_input %>%
    mutate(inc_lag_sum = rowSums(across(c(inc_lag1, inc_lag2, inc_lag3)), na.rm = TRUE)) %>%
    filter(as_of <= train_date)
  gravity_test_measles <- gravity_input %>%
      mutate(inc_lag_sum = rowSums(across(c(inc_lag1, inc_lag2, inc_lag3)), na.rm = TRUE)) %>%
      filter(as_of >= test_date)
  
  result <- optim(par = c(0.2, 0.2, 0.2, 0.2), 
                  fn = function(par) loss_fn_gbm(par, gravity_input_measles,
                                                 gravity_test_measles), 
                  method = "L-BFGS-B",
                  lower = c(-10, -10, -5, -5), upper = c(5,10, 10, 10))
  print(result)
  
  gbm_res <- gbm_fitting(gravity_input_measles, delta = result$par[1], alpha = result$par[2], 
              alpha_d = result$par[3], alpha_c = result$par[4], gravity_test_measles,
              data_filter = NULL)
  preds = gbm_res$preds
  df_test_scaled = gbm_res$df_test_scaled
  xgb_fit = gbm_res$xgb_fit
  
  
  df_test_scaled_gbm <- df_test_scaled %>%
  mutate(predicted_prob = preds,
      threshold_0.5 = ifelse(predicted_prob < 0.5, 0, 1),
      threshold_0.2 = ifelse(predicted_prob < 0.2, 0, 1),
      threshold_0.1 = ifelse(predicted_prob < 0.1, 0, 1))

  
  if (length(unique(df_test_scaled_gbm$first_onset)) == 2) {
    roc_obj <- pROC::roc(df_test_scaled_gbm$first_onset, df_test_scaled_gbm$predicted_prob)
    print(roc_obj)
    
    pROC::auc(roc_obj)
    
    plot(roc_obj, col = "blue", lwd = 2, main = "ROC Curve for GBM model")
    
    thresholds_to_plot <- c(0.5, 0.4, 0.3, 0.2, 0.1, 0.05)
    
    for (thr in thresholds_to_plot) {
      coords_point <- coords(roc_obj, x = thr, input = "threshold", ret = c("specificity", "sensitivity"))
      fpr <- 1 - coords_point["specificity"]
      tpr <- coords_point["sensitivity"]
      
      points(1-fpr, tpr, col = "red", pch = 19)
      text(1-fpr, tpr, labels = paste0("t=", thr), pos = 4, cex = 0.8)
    }
    
    actual <- df_test_scaled_gbm$first_onset
  predicted_prob <- df_test_scaled_gbm$predicted_prob

  
  # precrec용 데이터 객체 생성
  precrec_obj <- evalmod(scores = predicted_prob, labels = actual)
  
  # PR curve 그리기
  autoplot(precrec_obj, "PR") +
    ggtitle("Precision-Recall Curve") +
    theme_minimal()
  
  print(precrec::auc(precrec_obj))
  } else {
    message("Skipping ROC computation: `first_onset` has only one class.")
  }

  #roc_obj <- pROC::roc(df_test_scaled_gbm$first_onset, df_test_scaled_gbm$predicted_prob)
  
  print(table(df_test_scaled_gbm$first_onset, df_test_scaled_gbm$threshold_0.5))
  print(table(df_test_scaled_gbm$first_onset, df_test_scaled_gbm$threshold_0.2))
  print(table(df_test_scaled_gbm$first_onset, df_test_scaled_gbm$threshold_0.1))

  

  xgb.importance(model = xgb_fit) %>% 
    xgb.plot.importance()


  
  return(list(df_test_scaled_gbm = df_test_scaled_gbm, result = result))

}


```



```{r GBM_fitting, warning=FALSE}
preds_gbm = gbm_fitting_final(train_date = "2025-03-29", test_date = "2025-04-05", data_filter = NULL)



```


```{r rf_function}
library(randomForest)

rf_fit <- function(train_date, test_date,
                   delta = preds_gbm$result$par[1], alpha = preds_gbm$result$par[2], 
                   alpha_d = preds_gbm$result$par[3], alpha_c = preds_gbm$result$par[4],
                   data_filter = NULL){
  gravity_input_measles <- gravity_input %>%
    mutate(inc_lag_sum = rowSums(across(c(inc_lag1, inc_lag2, inc_lag3)), na.rm = TRUE)) %>%
    filter(as_of <= train_date)
  gravity_test_measles <- gravity_input %>%
      mutate(inc_lag_sum = rowSums(across(c(inc_lag1, inc_lag2, inc_lag3)), na.rm = TRUE)) %>%
      filter(as_of >= test_date)
  
  df_train <- lag_sum_cal_G(gravity_input_measles, delta = delta, alpha = alpha, 
                            alpha_d = alpha_d, alpha_c = alpha_c) %>%
    drop_na()
  if(!is.null(data_filter)){
    df_train <- df_train %>%
      mutate(as_of = as.Date(as_of)) %>%  # 문자열을 날짜로 변환
      group_by(county_x) %>%
      slice_max(as_of, n = 1) %>%
      ungroup()
  }
  
  df_train_scaled <- df_train %>%
    dplyr::mutate(across(
      .cols = -c(county_x, as_of, first_onset),
      .fns = scale
    ))
  
  df_test <- lag_sum_cal_G(gravity_test_measles, 
                           delta = delta, alpha = alpha, 
                            alpha_d = alpha_d, alpha_c = alpha_c) %>%
    drop_na()
  
  if(!is.null(data_filter)){
    df_test <- df_test %>%
      mutate(as_of = as.Date(as_of)) %>%  # 문자열을 날짜로 변환
      group_by(county_x) %>%
      slice_max(as_of, n = 1) %>%
      ungroup()
  }
  
  df_test_scaled <- df_test %>%
    dplyr::mutate(across(
      .cols = -c(county_x, as_of, first_onset),
      .fns = scale
    ))
  
  rf_fit <- randomForest(
    factor(first_onset) ~ G_mob + G_dist + G_catchment + vaccine + 
      pct_age_0_4 + pct_age_5_9 + pct_age_10_17 + pct_age_18_64 + pct_age_65_plus + 
      mennonite,
    data = df_train_scaled,
    ntree = 500,
    sampsize = c(100, 20)  # 0 class: 100, 1 class: 20
  )
  
  preds_rf <- predict(rf_fit, newdata = df_test_scaled, type = "prob")[,2]
  
  df_test_scaled_rf <- df_test_scaled %>%
    mutate(predicted_prob = preds_rf,
        threshold_0.5 = ifelse(predicted_prob < 0.5, 0, 1),
        threshold_0.2 = ifelse(predicted_prob < 0.2, 0, 1),
        threshold_0.1 = ifelse(predicted_prob < 0.1, 0, 1))
  
  
  if (length(unique(df_test_scaled_rf$first_onset)) == 2) {
    roc_obj <- pROC::roc(df_test_scaled_rf$first_onset, df_test_scaled_rf$predicted_prob)
    print(roc_obj)
    
    pROC::auc(roc_obj)
    
    plot(roc_obj, col = "blue", lwd = 2, main = "ROC Curve for RF model")
    
    thresholds_to_plot <- c(0.5, 0.4, 0.3, 0.2, 0.1, 0.05)
    
    for (thr in thresholds_to_plot) {
      coords_point <- coords(roc_obj, x = thr, input = "threshold", ret = c("specificity", "sensitivity"))
      fpr <- 1 - coords_point["specificity"]
      tpr <- coords_point["sensitivity"]
      
      points(1-fpr, tpr, col = "red", pch = 19)
      text(1-fpr, tpr, labels = paste0("t=", thr), pos = 4, cex = 0.8)
    }
    
    actual <- df_test_scaled_rf$first_onset
    predicted_prob <- df_test_scaled_rf$predicted_prob
    
    # precrec용 데이터 객체 생성
    precrec_obj <- evalmod(scores = predicted_prob, labels = actual)
    
    # PR curve 그리기
    autoplot(precrec_obj, "PR") +
      ggtitle("Precision-Recall Curve") +
      theme_minimal()
    
    print(precrec::auc(precrec_obj))
  } else {
    message("Skipping ROC computation: `first_onset` has only one class.")
  }
  
  print(table(df_test_scaled_rf$first_onset, df_test_scaled_rf$threshold_0.5))
  print(table(df_test_scaled_rf$first_onset, df_test_scaled_rf$threshold_0.2))
  print(table(df_test_scaled_rf$first_onset, df_test_scaled_rf$threshold_0.1))
  
  

  return(df_test_scaled_rf)
}
```


```{r rf_fitting}
preds_rf = rf_fit(train_date = "2025-03-29", test_date = "2025-04-05")

```


## Gradient Boosting with one data from one county


```{r filter_DK, warning=FALSE}
preds_gbm_DK = gbm_fitting_final(train_date = "2025-03-29", test_date = "2025-04-05", data_filter = "DK")


preds_rf_DK = rf_fit(train_date = "2025-03-29", test_date = "2025-04-05", data_filter = "DK")

```


```{r Longer_train, warning=FALSE}
preds_gbm = gbm_fitting_final(train_date = "2025-04-19", test_date = "2025-04-26", data_filter = NULL)

preds_rf = rf_fit(train_date = "2025-04-19", test_date = "2025-04-26")

```

```{r Longer_train_DK, warning=FALSE}
preds_gbm = gbm_fitting_final(train_date = "2025-04-19", test_date = "2025-04-26", data_filter = "DK")

preds_rf = rf_fit(train_date = "2025-04-19", test_date = "2025-04-26", data_filter = "DK")

```